### ISSUE TITLE
Problem with sockets / cable

### ISSUE THREAD

**Issue by haviduck** [KevinBongart/cards_against_humanity#41]
hey man! 
Great stuff, Im actually doing a similar thing to be able to have a beer and a game with friends in a side-by-side webinar grid. 
your game would fit perfectly - best cah clone ive found.
but im having a hard time getting the signalling up and running. i have to manually refresh the page to see the updated changes from db ingame. 

Read up on puma and actioncable which looks to be the culprit. Websockets isnt giving any errors, and neither is the console, however it is listening on localhost:3000 and :::1:3000 instead of what im used to.

Im running a very basic nginx reverse proxy to puma and ssl via haproxy on ubuntu 18.04. 
Ive tried a whole ton of variations of nginx confs, puma binds and ports. 

ruby is completely new to me so any pointers are greatly appreciated and i really wouldnt ask so early but.. beer. isolation..

**edit**
cable gets stuck at 101 during upgrade. any ideas?

**Comment by KevinBongart** [comment]
Hi, I'm not familiar with anything upstream to the app, but other than websocket issues, it could be that the server isn't streaming changes. I don't think I've updated the documentation to reflect this, but it needs Sidekiq to run, which streams in the background.

In addition to starting the Puma web server, try `sidekiq -c 2` which starts 2 Sidekiq workers. You should see in the Sidekiq logs that the workers are processing jobs, and there's only one type of job right now: streaming updates to clients.

Let me know how that works, I'll update the README on my end.

**Comment by haviduck** [comment]
that did the trick, thank you! the 101 pending error was not relevant and a minor tweak to nginx was all it took. 
but i wasnt able to run this as daemon in a oneliner.. 

do you know a way to pull that off? like bundle exec rails server sidekiq -c 2  -d

**Comment by KevinBongart** [comment]
Glad to hear that!

To start several processes in one line, a good practice is to use a Procfile that defines each process (web and workers, in our case) with the associated command. That's how Heroku and other PaaS start and scale each process.

If you want to take a stab at adding a Procfile and some Ruby gem that can start/stop these processes, a pull request could help other people in your situation and would be greatly appreciated!

**Comment by KevinBongart** [comment]
> If you want to take a stab at adding a Procfile and some Ruby gem that can start/stop these processes, a pull request could help other people in your situation and would be greatly appreciated!

@haviduck I realized there was already a Procfile, so I updated the README in this PR: #46

**Comment by haviduck** [comment]
> > If you want to take a stab at adding a Procfile and some Ruby gem that can start/stop these processes, a pull request could help other people in your situation and would be greatly appreciated!
> 
> @haviduck I realized there was already a Procfile, so I updated the README in this PR: #46

Thats amazing man, im getting the hang of it now, thanks for good explanations and patience.
