### ISSUE TITLE
Roomcreator 

### ISSUE THREAD

**Issue by haviduck** [KevinBongart/cards_against_humanity#51]
Heya, 
pushing forward and i see a need for a moderator-ish role. the room creator for example which should get permission to kick other users and force-end rounds. gonna try and edit the schema to add creatorid and see if i cant migrate or whatever its called in ruby.

integrated kick user function, so to prevent trollmayhem it would be great, but ive no idea how to do a  pull request.

**Comment by haviduck** [comment]
For those interested: 
https://github.com/haviduck/cards_against_humanity/commit/9ac002f87f684f5ab38f1b5b9f464a92b301c3da

**Comment by KevinBongart** [comment]
@haviduck Thanks for the suggestion. Take a look at the official GitHub help for creating pull requests: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests

In your case, the changes are in the commit you listed above, so you'll first need to create a branch that isolates this commit compared to the `master` branch of my repo, and then open a PR for your new branch to the `master branch` of my repo.

The pull request will thus says "@haviduck would like to contribute these changes to `KevinBongart/cards_against_humanity`"

**Comment by haviduck** [comment]
> @haviduck Thanks for the suggestion. Take a look at the official GitHub help for creating pull requests: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests
> 
> In your case, the changes are in the commit you listed above, so you'll first need to create a branch that isolates this commit compared to the `master` branch of my repo, and then open a PR for your new branch to the `master branch` of my repo.
> 
> The pull request will thus says "@haviduck would like to contribute these changes to `KevinBongart/cards_against_humanity`"

thanks, will try - and please bare with me if i eff up at first :)

**Comment by KevinBongart** [comment]
Yes of course! I'll be happy to help you, and a PR will be the ideal place to discuss the code changes and iterate

**Comment by haviduck** [comment]
i get the jist of it, its just that when i make a branch -everything- follows. and if i get this correctly i am to only submit the files in question. so just gonna figure that bit out then ill add each feature ive added as a pull request.

**Comment by KevinBongart** [comment]
You can make a branch that includes only commits in this repo, call it `upstream` for instance. Here's how to configure my repo as the upstream remote: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork

Then create a new branch off `upstream`, let's call it the `moderator_feature` branch, and [cherry-pick](https://stackoverflow.com/questions/9339429/what-does-cherry-picking-a-commit-with-git-mean) the commits you want to submit.

This way, your `master` branch includes all your various changes, the `upstream` branch is tracking my `master` branch, and the `moderator` branch is `upstream` plus the moderator-related commits you want to submit here.

In my local repo:

- `master`: my code, including the most recent commits (`kevin_commit_1`, `kevin_commit_2`, …)

In your local repo:

- `master`: my code, plus all your changes (`kevin_commit_1`, `kevin_commit_2`, …, `haviduck_commit_1`, `haviduck_commit_2`, etc.)
- `upstream`: a branch in your repo that mirrors my `master` branch (`kevin_commit_1`, `kevin_commit_2`, …)
- `moderator_feature`: a branch that only differs from `upstream` by the commits related to the moderator feature (`kevin_commit_1`, `kevin_commit_2`, …, `haviduck_commit_2`)

And your pull request would then be requesting that the branch `haviduck/moderator_feature` be merged into `kevin/master`, ultimately resulting in `kevin_commit_1`, `kevin_commit_2`, …, `haviduck_commit_2` being part of this repo and available to everyone else.

Git has an unnecessary complex interface but that's the standard most people use, so please don't hesitate to let me know if you need more pointers.

**Comment by haviduck** [comment]
Yeah i appreciate that guidance immensely. Ive postponed learning this stuff so i guess now is the time. Gonna try more tomorrow and hope fully a pr Will appear! :)

**Comment by haviduck** [comment]
allright, ive tried. i started out wrong so ive had to do some hackish stuff to only have the files in question. please review and advise :)
